default_context:
  project_name: 'GCMD Keyword Classifier'
  project_slug: 'gcmd-keyword-classifier'
  domain_main: 'gkrtest.nasa-impact.net'
  domain_staging: 'stag.gkrtest.nasa-impact.net'
  docker_swarm_stack_name_main: 'gkrtest-nasa-impact-net'
  docker_swarm_stack_name_staging: 'stag-gkrtest-nasa-impact-net'
  secret_key: 'ba9d5cd638dda648f5c4dee9e7634c8368c129cb6b06c2ab3dea25410cd43b0b'
  first_superuser: 'ashish.acharya14@gmail.com'
  first_superuser_password: 'ba9d5cd638dda648f5c4dee9e7634c8368c129cb6b06c2ab3dea25410cd43b0b'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.gkrtest.nasa-impact.net", "https://stag.gkrtest.nasa-impact.net", "https://gkrtest.nasa-impact.net", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gkrtest.nasa-impact.net'
  postgres_password: 'ba9d5cd638dda648f5c4dee9e7634c8368c129cb6b06c2ab3dea25410cd43b0b'
  pgadmin_default_user: 'ashish.acharya14@gmail.com'
  pgadmin_default_user_password: 'ba9d5cd638dda648f5c4dee9e7634c8368c129cb6b06c2ab3dea25410cd43b0b'
  traefik_constraint_tag: 'gkrtest.nasa-impact.net'
  traefik_constraint_tag_staging: 'stag.gkrtest.nasa-impact.net'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ba9d5cd638dda648f5c4dee9e7634c8368c129cb6b06c2ab3dea25410cd43b0b'
  sentry_dsn: 'https://7fc36ae0211f43bea2113467a94effba@o464007.ingest.sentry.io/5471067'
  docker_image_prefix: 'gkr/'
  docker_image_backend: 'gkr/backend'
  docker_image_celeryworker: 'gkr/celeryworker'
  docker_image_frontend: 'gkr/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
